name: The Film Dream Digital Studios
analytics:
  google: UA-64070424-1
purpose:
  - type: external
    url: 'http://thefilmdream.com'
    label: thefilmdream.com
github: true
description: Powering your Brands Through Digital Stories
author:
  name: The Film Dream Digital Studios
  url: 'http://thefilmdream.com'
  email: thefilmdream@icloud.com
cta:
  bucket: null
  version: null
  domain: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/22821b08-ce97-435e-9b3d-b1adb1af0d5d.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/22821b08-ce97-435e-9b3d-b1adb1af0d5d.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
layout_spectrum: 0.8396684448234737
color:
  lightness: 0.9011626951396465
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  saturation: 0.04707157495431602
  brandStrength: 0.9025435189250857
  rhythmicContrast: 0.7055696463212371
content_rating:
  adult: false
typography_spectrum: 0.2429757060017437
opengraph: {}
title: The Film Dream Digital Studios
url: 'http://thefilmdreamdigitalstudios.com'
