name: The Film Dream Digital Studios
analytics:
  google: UA-64070424-1
purpose:
  - type: external
    url: 'http://thefilmdream.com'
    label: thefilmdream.com
github: true
description: Powering your Brands Through Digital Stories
author:
  name: The Film Dream Digital Studios
  url: 'http://thefilmdream.com'
  email: thefilmdream@icloud.com
cta:
  bucket: null
  version: null
  domain: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.8396684448234737
color:
  lightness: 0.9011626951396465
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  saturation: 0.04707157495431602
  brandStrength: 0.9025435189250857
  rhythmicContrast: 0.7055696463212371
content_rating:
  adult: false
typography_spectrum: 0.2429757060017437
opengraph: {}
title: The Film Dream Digital Studios
url: 'https://thegrid.ai/danpascual/'
